opt_in_rules:
  - force_cast
  - force_try
  - force_unwrapping

line_length:
  warning: 120
  error: 150

type_body_length:
  warning: 300
  error: 400

strict: true

excluded:
  - .build
  - Carthage
  - Pods
  - iOS/Sample/StashNativeSample/DerivedData
  - iOS/Sample/StashNativeSample/build
  - iOS/Sample/StashNativeSample/scratchpad
